### ISSUE TITLE
validate that CloudFront for Haul is working

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-itcloud/scl3-migration-project#1]

**Comment by danielhartnell** [comment]
Public Suffix is the only site configured to use CloudFront right now. The relevant code can be seen here:

https://github.com/mozilla-it/haul/blob/master/nubis/terraform/sites.tf#L126-L140

To validate functionality, we should hit the CloudFront distribution while passing in the publicsuffix.org `Host` header value and see if it successfully retrieves and returns the content from the origin (Haul ELB endpoint - so Varnish or Apache).

**Comment by danielhartnell** [comment]
Whoops! Looks like I overlooked something. I can review tomorrow.

```
18:19:28 
18:19:28 
18:19:28 
18:19:28 Error: module "cloudfront": "count" is not a valid argument
18:19:28 
18:19:28 
18:19:28 
18:19:28 Error: module "cloudfront": "domains" is not a valid argument
18:19:28 
18:19:28 
18:19:28 
18:19:28 Error: module "cloudfront": "count" is not a valid argument
18:19:28 
18:19:28 
18:19:28 
18:19:28 Error: module "cloudfront": "count" is not a valid argument
18:19:28 
18:19:28 
18:19:28 
18:19:28 Error: module "cloudfront": "domains" is not a valid argument
18:19:28 
18:19:28 
```

**Comment by mgreensmith** [comment]
I'm less and less convinced that Cloudfront > ELB > Traefik > Varnish > Apache is an acceptable static site hosting path.
