### ISSUE TITLE
Cutover plan for startpage

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/scl3-migration-project#13]
https://docs.google.com/document/d/1z4n-pIqLODZdXibyJr6HyerYSzyaL2IEB1ssydGk4Fw/edit?usp=sharing

What do we still need to do to go live with this?

At least answer this question:
"The Apache configuration under Haul needs to include all relevant redirects "

**Comment by mgreensmith** [comment]
- [ ] Site content in AWS is identical to content served from the datacenter Use a tool like https://github.com/evolvingweb/sitediff or do it manually.
- [ ] All required HTTP headers are present (as compared to the datacenter site)
- [ ] The site has been audited through Observatory an has an acceptable score.
- [ ] Site content is sourced from the canonical github repo, not a personal fork.
- [ ] MOC has a basic monitor for the site and a runbook for incident management.
- [ ] DNS has been audited and we know all of the domains that point to the app, TTLs are set low
- [ ] We are serving correct TLS certificates for production domains.
- [ ] Some capacity planning based on current production traffic. Review Zeus logs, New Relic, Apache logs

**Comment by joekrejci** [comment]
start.mozilla.org successfully migrated to Nubis land.
