### ISSUE TITLE
Audit virtual redirect domains

### ISSUE THREAD

**Issue by mgreensmith** [mozilla-itcloud/scl3-migration-project#24]
Make sure we don't have long TTLs on SOA records, in case we need to move domains.

**Comment by danielhartnell** [comment]
These have the highest TTLs. Nothing too concerning here:

```
firefox.hu: 3600
firefox.lt: 3600
mozilla.hu: 3600
popcornjs.org: 3600
www.impactmozilla.com: 3600
www.mozilla.org.uk: 3600
docs.services.mozilla.com: 86400
fxfeeds.mozillazine.org: 86400
```

Initial audit work was tracked here:

https://docs.google.com/spreadsheets/d/1Ns1ov_upA1eV0SCKy9j3unAi_1lRu_m7IhNA4FGLVoE/edit#gid=1080091738

Some sites have been migrated already and they are running under Haul. Some of these apex domains will have DNS records in Route 53 using an alias record set to point to the Haul domain name.
