### ISSUE TITLE
fix website-archive.mozilla.org source repository

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-itcloud/scl3-migration-project#5]
The svn repository no longer exists and the site content should be moved to GitHub.

**Comment by mgreensmith** [comment]
Looks like this was done, but moved to a different haul build: 'www-archive' works and pulls from git, 'archive' pulls from SVN and has never worked. We should remove the 'archive' build. https://github.com/mozilla-itcloud/maintenance-project/issues/9

**Comment by gozer** [comment]
Nope, archive.mozilla.org and website-archive.mozilla.org are most definitely *not* the same sites.

**Comment by gozer** [comment]
archive pulls from SVN and has worked at some point before svn.m.o was decomisionned. The build history just doesn't show it, it gets cleaned up after a while.
